version: "3.9"

services:
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}